// ── META DATA — NAIC 2026 New Orleans (10 Jun 2026, 3752 players) ──────────────
const META_DECKS = [
  {
    id: "dragapult",
    name: "Dragapult ex",
    placement: "🥇 #1 NAIC 2026",
    player: "Diversas listas Top Cut",
    event: "NAIC 2026 — New Orleans",
    metaShare: 48.15,
    tier: "S",
    color: "#7F77DD",
    emoji: "👻",
    desc: "Spread damage com Phantom Dive + disrupção com Crushing Hammer. Deck dominante do formato pós-rotação.",
    strengths: ["Consistência absurda", "Spread damage passivo", "Flexível em parceiros"],
    weaknesses: ["Mirror match complexo", "Depende de coin flips (Crusher)", "Vulnerável a Item lock"],
    keyCards: ["dragapult ex","drakloak","dreepy","dusknoir","duskull","dudunsparce","dunsparce","professor's research","ultra ball","rare candy","boss's orders","night stretcher","crushing hammer","calamitous wasteland"],
    optionalCards: ["moltres","radiant charizard","dawn","buddy-buddy poffin"]
  },
  {
    id: "zoroark",
    name: "N's Zoroark",
    placement: "🥈 #2 NAIC 2026",
    player: "Annabelle O.",
    event: "NAIC 2026 — New Orleans",
    metaShare: 7.56,
    tier: "A",
    color: "#D85A30",
    emoji: "🦊",
    desc: "Atacante rápido da linha N com aceleração de energia via N's Zorua. Forte no early game.",
    strengths: ["Setup rápido", "Alto dano por energia", "Surpresa no meta"],
    weaknesses: ["Dependente de draws iniciais", "Fraco contra controle", "Pouca recuperação"],
    keyCards: ["n's zoroark","n's zorua","n's zoroark ex","ultra ball","boss's orders","night stretcher","lillie's determination","rare candy"],
    optionalCards: ["iono","professor's research","buddy-buddy poffin"]
  },
  {
    id: "alakazam",
    name: "Alakazam",
    placement: "🏅 Top 5 NAIC 2026",
    player: "Travis C. / Rahul Reddy",
    event: "NAIC 2026 — New Orleans",
    metaShare: 6.81,
    tier: "A",
    color: "#EF9F27",
    emoji: "🥄",
    desc: "Powerful Hand sem Iono no formato. Constrói mão gigante e causa dano proporcional ao tamanho da mão.",
    strengths: ["Sem counter efetivo pós-rotação", "Escalável", "One-shot qualquer coisa com mão cheia"],
    weaknesses: ["Setup lento", "Vulnerável a disruption", "Dependente de não tomar dano cedo"],
    keyCards: ["alakazam","kadabra","abra","ultra ball","rare candy","boss's orders","night stretcher","professor's research"],
    optionalCards: ["iono","buddy-buddy poffin","genesect"]
  },
  {
    id: "crustle",
    name: "Crustle",
    placement: "🏅 Top 4 NAIC 2026",
    player: "Liam Halliburton",
    event: "NAIC 2026 — New Orleans",
    metaShare: 5.19,
    tier: "A",
    color: "#3B6D11",
    emoji: "🦀",
    desc: "Deck de prize denial com Crustle. Estratégia única que dificulta o oponente pegar prêmios.",
    strengths: ["Prize denial forte", "Surpreendente no meta", "Resiliente"],
    weaknesses: ["Setup específico", "Dependente da estratégia", "Lento"],
    keyCards: ["crustle","dwebble","ultra ball","boss's orders","night stretcher"],
    optionalCards: ["iono","professor's research"]
  },
  {
    id: "slowking",
    name: "Slowking / Control",
    placement: "🏅 Top 4 NAIC 2026",
    player: "Múltiplos jogadores",
    event: "NAIC 2026 — New Orleans",
    metaShare: 5.19,
    tier: "A",
    color: "#D4537E",
    emoji: "🐚",
    desc: "Controle via Slowking ex. Destrói a mão do oponente consistentemente.",
    strengths: ["Disruption poderosa", "Controlado e preciso", "Bom contra Stage 2"],
    weaknesses: ["Lento", "Fraco contra aggro", "Empates frequentes"],
    keyCards: ["slowking ex","slowpoke","ultra ball","boss's orders","night stretcher","iono","professor's research"],
    optionalCards: ["radiant alakazam","fan rotom"]
  },
  {
    id: "grimmsnarl",
    name: "Grimmsnarl / Froslass",
    placement: "Top 16 EUIC 2026",
    player: "Múltiplos jogadores",
    event: "EUIC 2026 — Londres",
    metaShare: 3.2,
    tier: "B",
    color: "#1D9E75",
    emoji: "❄️",
    desc: "Spread damage com Froslass + redistribuição Munkidori. Tier 1-2 do meta atual, forte contra Stage 2.",
    strengths: ["Spread único", "Forte contra Gardevoir/Charizard", "Barato para montar"],
    weaknesses: ["Risco de bricar", "Matchups ruins contra aggro", "Alta taxa de empate"],
    keyCards: ["marnie's grimmsnarl ex","marnie's morgrem","marnie's impidimp","froslass","snorunt","munkidori","lillie's determination","spikemuth gym","night stretcher","rare candy","boss's orders","poké pad","team rocket's petrel","darkness energy"],
    optionalCards: ["budew","tatsugiri","yveltal","buddy-buddy poffin","pegador superior"]
  },
  {
    id: "mewtwo",
    name: "Rocket's Mewtwo ex",
    placement: "Top 16 NAIC 2026",
    player: "Múltiplos jogadores",
    event: "NAIC 2026 — New Orleans",
    metaShare: 1.19,
    tier: "B",
    color: "#885AF8",
    emoji: "🧬",
    desc: "Atacante psíquico pesado da Equipe Rocket com aceleração de energia via Spidops.",
    strengths: ["Alto dano por energia", "Aceleração rápida", "Surpreendente"],
    weaknesses: ["Pouca flexibilidade", "Vulnerável a Darkrai", "Meta share baixo"],
    keyCards: ["team rocket's mewtwo ex","team rocket's spidops","team rocket's petrel","boss's orders","night stretcher","darkness energy"],
    optionalCards: ["team rocket's crobat ex","team rocket's articuno"]
  },
  {
    id: "ogerpon",
    name: "Ogerpon / Meganium Box",
    placement: "Top 8 NAIC 2026",
    player: "Múltiplos jogadores",
    event: "NAIC 2026 — New Orleans",
    metaShare: 3.56,
    tier: "A",
    color: "#639922",
    emoji: "🌿",
    desc: "Aceleração de energia com Meganium + Ogerpon ex. One-shot Dragapult com 4 energias.",
    strengths: ["OHKO em qualquer coisa com energia suficiente", "Counter natural ao Dragapult", "Ramp poderoso"],
    weaknesses: ["Precisa de muitas energias ativas", "Setup de 2-3 turnos", "Vulnerável a disruption"],
    keyCards: ["teal mask ogerpon ex","meganium","bayleef","chikorita","ultra ball","rare candy","boss's orders","dawn","bug catching set","forest of vitality"],
    optionalCards: ["mega venusaur ex","buddy-buddy poffin","night stretcher"]
  }
];
